### PR TITLE
Fixed the fetch bug and switched to chatGPT api

### PR DESCRIPTION
**Pull request by arian81**
Co-authored-by: Krish <hello@krishkrish.com>

### CODE REVIEW

**Comment by junukwon7** [comment]
Great work!

However, since I only have a limited knowledge about TS, I couldn't figure out what triggered, and how to fix the error below.

I also got the same error from @abielzulio 's wip branch, but didn't on the main branch.

```text
$ npm run-script build

> build
> ray build -e dist

info  -  entry points [src/result.tsx src/saved.tsx src/history.tsx]
src/result.tsx:200:22 - error TS2345: Argument of type '(prev: ChatAnswer[]) => (ChatAnswer | { partialAnswer: ChatMessage; done: boolean; answer: string; convoId?: string | undefined; parentId?: string | undefined; savedAt?: string | undefined; id: string; question: string; createdAt: string; })[]' is not assignable to parameter of type 'SetStateAction<ChatAnswer[]>'.
  Type '(prev: ChatAnswer[]) => (ChatAnswer | { partialAnswer: ChatMessage; done: boolean; answer: string; convoId?: string | undefined; parentId?: string | undefined; savedAt?: string | undefined; id: string; question: string; createdAt: string; })[]' is not assignable to type '(prevState: ChatAnswer[]) => ChatAnswer[]'.
    Type '(ChatAnswer | { partialAnswer: ChatMessage; done: boolean; answer: string; convoId?: string | undefined; parentId?: string | undefined; savedAt?: string | undefined; id: string; question: string; createdAt: string; })[]' is not assignable to type 'ChatAnswer[]'.
      Type 'ChatAnswer | { partialAnswer: ChatMessage; done: boolean; answer: string; convoId?: string | undefined; parentId?: string | undefined; savedAt?: string | undefined; id: string; question: string; createdAt: string; }' is not assignable to type 'ChatAnswer'.
        Type '{ partialAnswer: ChatMessage; done: boolean; answer: string; convoId?: string | undefined; parentId?: string | undefined; savedAt?: string | undefined; id: string; question: string; createdAt: string; }' is not assignable to type 'ChatAnswer'.
          Types of property 'partialAnswer' are incompatible.
            Type 'ChatMessage' is not assignable to type 'string'.

200           setAnswers((prev) => {
                         ~~~~~~~~~~~

src/result.tsx:334:15 - error TS2552: Cannot find name 'setConversationId'. Did you mean 'setConversation'?

334               setConversationId(uuidv4());
                  ~~~~~~~~~~~~~~~~~

  src/result.tsx:53:24
    53   const [conversation, setConversation] = useState<string[]>([]);
                              ~~~~~~~~~~~~~~~
    'setConversation' is declared here.

src/views/answer-detail.tsx:19:83 - error TS2339: Property 'conversationId' does not exist on type 'Answer'.

19             <List.Item.Detail.Metadata.Label title="Conversation ID" text={answer.conversationId} />
                                                                                     ~~~~~~~~~~~~~~


Found 3 errors in 2 files.

Errors  Files
     2  src/result.tsx:200
     1  src/views/answer-detail.tsx:19
TypeScript check failed (exit status 2)
```
```
ENV:
npm 9.5.0
node 19.7.0
m1 macbook pro (ventura)
```

**Comment by sunrisewestern** [comment]
Still have fetch error using this PR.

"""
Error: Invalid environment; fetch is not defined

ChatGPT:result.tsx:52:64

---
49: };
50:
51: export default function ChatGPT() {
52:   const [parentMessageId, setParentMessagId] = useState<string>("");
53:   const [conversation, setConversation] = useState<string[]>([]);
54:   const [answers, setAnswers] = useState<ChatAnswer[]>([]);
55:   const [savedAnswers, setSavedAnswers] = useState<Answer[]>([]);
---

wr:index.js:5:2490
    at ray-navigation-stack
Ro:index.js:5:2088
event -  stopped development mode
"""

**Comment by arian81** [comment]
> Great work!
> 
> However, since I only have a limited knowledge about TS, I couldn't figure out what triggered, and how to fix the error below.
> 
> After `npm install`
> 
> ```
> $ npm run-script build
> 
> > build
> > ray build -e dist
> 
> info  -  entry points [src/result.tsx src/saved.tsx src/history.tsx]
> src/result.tsx:200:22 - error TS2345: Argument of type '(prev: ChatAnswer[]) => (ChatAnswer | { partialAnswer: ChatMessage; done: boolean; answer: string; convoId?: string | undefined; parentId?: string | undefined; savedAt?: string | undefined; id: string; question: string; createdAt: string; })[]' is not assignable to parameter of type 'SetStateAction<ChatAnswer[]>'.
>   Type '(prev: ChatAnswer[]) => (ChatAnswer | { partialAnswer: ChatMessage; done: boolean; answer: string; convoId?: string | undefined; parentId?: string | undefined; savedAt?: string | undefined; id: string; question: string; createdAt: string; })[]' is not assignable to type '(prevState: ChatAnswer[]) => ChatAnswer[]'.
>     Type '(ChatAnswer | { partialAnswer: ChatMessage; done: boolean; answer: string; convoId?: string | undefined; parentId?: string | undefined; savedAt?: string | undefined; id: string; question: string; createdAt: string; })[]' is not assignable to type 'ChatAnswer[]'.
>       Type 'ChatAnswer | { partialAnswer: ChatMessage; done: boolean; answer: string; convoId?: string | undefined; parentId?: string | undefined; savedAt?: string | undefined; id: string; question: string; createdAt: string; }' is not assignable to type 'ChatAnswer'.
>         Type '{ partialAnswer: ChatMessage; done: boolean; answer: string; convoId?: string | undefined; parentId?: string | undefined; savedAt?: string | undefined; id: string; question: string; createdAt: string; }' is not assignable to type 'ChatAnswer'.
>           Types of property 'partialAnswer' are incompatible.
>             Type 'ChatMessage' is not assignable to type 'string'.
> 
> 200           setAnswers((prev) => {
>                          ~~~~~~~~~~~
> 
> src/result.tsx:334:15 - error TS2552: Cannot find name 'setConversationId'. Did you mean 'setConversation'?
> 
> 334               setConversationId(uuidv4());
>                   ~~~~~~~~~~~~~~~~~
> 
>   src/result.tsx:53:24
>     53   const [conversation, setConversation] = useState<string[]>([]);
>                               ~~~~~~~~~~~~~~~
>     'setConversation' is declared here.
> 
> src/views/answer-detail.tsx:19:83 - error TS2339: Property 'conversationId' does not exist on type 'Answer'.
> 
> 19             <List.Item.Detail.Metadata.Label title="Conversation ID" text={answer.conversationId} />
>                                                                                      ~~~~~~~~~~~~~~
> 
> 
> Found 3 errors in 2 files.
> 
> Errors  Files
>      2  src/result.tsx:200
>      1  src/views/answer-detail.tsx:19
> TypeScript check failed (exit status 2)
> ```
> 
> ```
> ENV:
> npm 9.5.0
> node 19.7.0
> m1 macbook pro (ventura)
> ```

This error doesn't break the program cause I think it's related to the chat history.

**Comment by arian81** [comment]
> Still have fetch error using this PR.
> 
> ```
> 14:44:16.516 The above error occurred in the <ChatGPT> component:
> 
>     at ChatGPT (/Users/cxx/.config/raycast/extensions/chatgpt/result.js:108326:75)
>     at wr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:2490)
>     at ray-navigation-stack
>     at Ro (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:2088)
>     at Suspense
>     at vr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:4:4675)
>     at ray-root
>     at Yn (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:3000)
> 
> React will try to recreate this component tree from scratch using the error boundary you provided, InternalErrorBoundary.
> Error: Invalid environment; fetch is not defined
> 
> ChatGPT:result.tsx:52:64
> 
> ---
> 49: };
> 50:
> 51: export default function ChatGPT() {
> 52:   const [parentMessageId, setParentMessagId] = useState<string>("");
> 53:   const [conversation, setConversation] = useState<string[]>([]);
> 54:   const [answers, setAnswers] = useState<ChatAnswer[]>([]);
> 55:   const [savedAnswers, setSavedAnswers] = useState<Answer[]>([]);
> ---
> 
> wr:index.js:5:2490
>     at ray-navigation-stack
> Ro:index.js:5:2088
> event -  stopped development mode
> ```

oh I think i know what the issue is Imma fix it rn

**Comment by arian81** [comment]
@sunrisewestern The issue should be resolved now.

**Comment by sunrisewestern** [comment]
> @sunrisewestern The issue should be resolved now.

Cool.  It is fixed.

**Comment by arian81** [comment]
@junukwon7 The original creator of extension will work to get the chat history fixed at some point. The api used to communicate with chatGPT has drastically changed since this project was made so a lot of the features broke and require rewrites.

**Pull request closed without merging**
