### PR TITLE
feat: move model selection to ask detail view

### PR DESCRIPTION
**Pull request by kale5195**
Hi Abiel,

I made some changes to move model selection from right corner into ask detail view.

Here is a video for this feature:

I use Command + Shift + U to trigger the ask command

https://user-images.githubusercontent.com/95554104/223593998-0800e96d-39ea-423d-b77e-7af9db48c44c.mov

Not sure if you like this PR... Feel free to close it if you dislike or you can implement your own..

### CODE REVIEW

**Comment by abielzulio** [comment]
What's the main reason of this PR? Which part of the current layout/experience that you don't like/missing? Could you elaborate more on that?

**Comment by kale5195** [comment]
Currently, in order to select a model, you have to click command + P. However, with this PR, this step is removed.

Furthermore, when selecting long text, it can be difficult to display it in the search text input. It would be better to display it in the item detail view.

**Comment by abielzulio** [comment]
> Currently, in order to select a model, you have to click command + P. However, with this PR, this step is removed.

Yes, the current flow does need an extra step to select the model but this gives the user flexibility to change their model on-the-fly rather has a fixed model selection from the beginning like yours.

> Furthermore, when selecting long text, it can be difficult to display it in the search text input. It would be better to display it in the item detail view.

How do you handle conversation (multiple on-going chat) then?

**Comment by kale5195** [comment]
> has a fixed model selection from the beginning like yours.

Mine has same flexibility, it just move the dropdown into view.  If there is no matched prompts, it will became default model.
Also you can long press command key to apply custom prompts

**Comment by abielzulio** [comment]
> > has a fixed model selection from the beginning like yours.
> 
>
> Mine has same flexibility, it just move the dropdown into view.  If there is no matched prompts, it will became default model.
> 
> Also you can long press command key to apply custom prompts
> 

Yes, but how do you handle the conversation then?

**Comment by kale5195** [comment]
@abielzulio I didn't change the conversation part, after clicking enter, it will reuse the conversation part you build

**Comment by abielzulio** [comment]
Checkout my proposal on [`feat/use-full-input-init`](https://github.com/abielzulio/chatgpt-raycast/tree/feat/use-full-input-init) branch and please let me know what you think of that.

I agree with you that sometimes the user needs a bigger input space when asking a question but disagree with moving the question from the `search bar` into the `detailed view` making the upcoming conversation doesn't look seamless and consistent.

**Comment by kale5195** [comment]
👍🏻 use full input solve the problem of large text, but is it possible to add a shortcut for model selection? 

I can close this PR for now

**Pull request closed without merging**
