### PR TITLE
add proxy config

### PR DESCRIPTION
**Pull request by k9982874**
Allow the user access the OpenAPI behind the proxy

### CODE REVIEW

**Comment by abielzulio** [comment]
What's the real use case behind this? Could you elaborate more on what are you trying to achieve/do using a custom proxy?

**Comment by k9982874** [comment]
> Owner

OpenAPI has been blocked in China. China users have to access the APIs through the proxy.

**Comment by abielzulio** [comment]
Have you added the `axios` module to the `package.json`'s `dependencies`? Or does it able to run without the `axios` module? Also, could you rebase your PR based on the latest commit?

**Comment by k9982874** [comment]
> Have you added the `axios` module to the `package.json`'s `dependencies`? Or does it able to run without the `axios` module? Also, could you rebase your PR based on the latest commit?

The axios is a dependency of the OpenAI node module. So, it embeds into the project already.

**Pull request merged**
